services:
  - type: web
    name: metropt-predictive-maintenance
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: metropt-redis
          property: connectionString
  
  - type: redis
    name: metropt-redis
    plan: free
    region: ohio
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
