services:
  - type: web
    name: metropt-predictive-maintenance
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: metropt-redis
          property: connectionString
  
  - type: redis
    name: metropt-redis
    plan: free
    region: ohio
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  - type: web
    name: metropt-dashboard
    runtime: static
    plan: free
    region: ohio
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    rootDir: frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: metropt-predictive-maintenance
          property: url
