import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from pathlib import Path
import sys

st.set_page_config(
    page_title="MetroPT APU Predictive Maintenance Dashboard",
    page_icon="🚆",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Header & Branding
st.title("🚆 MetroPT APU Predictive Maintenance Dashboard")
st.markdown("**Real-Time Air Production Unit Early-Warning & Diagnostic System (Porto Fleet)**")

# Sidebar Configuration
st.sidebar.header("⚙️ Fleet Control Panel")
apu_selection = st.sidebar.selectbox("Select Train Unit", ["APU-Unit-01 (Porto Fleet)", "APU-Unit-02 (Backup)", "APU-Unit-03 (Depot)"])
st.sidebar.markdown("---")
st.sidebar.success("System Status: **Active Cloud Simulation**\nData Frequency: **10s Sampling**")

# Telemetry Data Generator
np.random.seed(42)
time_index = pd.date_range("2026-08-24 12:00:00", periods=50, freq="10s")
df_telemetry = pd.DataFrame({
    "TP2": np.random.normal(8.5, 0.3, 50),
    "TP3": np.random.normal(9.8, 0.4, 50),
    "H1": np.random.normal(0.05, 0.01, 50),
    "Motor_current": np.random.normal(11.5, 0.8, 50),
    "Oil_temperature": np.random.normal(55.0, 1.2, 50)
}, index=time_index)

# Top Metrics Row
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(label="2 Hours Horizon Risk", value="2.1%", delta="Low Risk")

with col2:
    st.metric(label="4 Hours Horizon Risk", value="4.8%", delta="Normal")

with col3:
    st.metric(label="8 Hours Horizon Risk", value="12.4%", delta="Watch Window")

with col4:
    st.markdown("### Status\n`:green[NORMAL]`")

st.markdown("---")

# Main Content Layout: Charts & Diagnostic Cards
left_col, right_col = st.columns([2, 1])

with left_col:
    st.subheader("📈 Real-Time Telemetry & Pressure Trends")
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df_telemetry.index, y=df_telemetry["TP2"], mode='lines', name='TP2 (Compressor Pressure)', line=dict(color='#1f77b4', width=2)))
    fig.add_trace(go.Scatter(x=df_telemetry.index, y=df_telemetry["TP3"], mode='lines', name='TP3 (Reservoir Pressure)', line=dict(color='#2ca02c', width=2)))
    fig.add_trace(go.Scatter(x=df_telemetry.index, y=df_telemetry["H1"], mode='lines', name='H1 (Filter Pressure Drop)', line=dict(color='#ff7f0e', width=1.5)))
    fig.add_trace(go.Scatter(x=df_telemetry.index, y=df_telemetry["Motor_current"], mode='lines', name='Motor Current (A)', line=dict(color='#d62728', width=1.5, dash='dot')))
    
    fig.update_layout(
        title="Compressor Sensor Telemetry Trends",
        xaxis_title="Time Step / Timestamp",
        yaxis_title="Sensor Value",
        template="plotly_dark",
        margin=dict(l=40, r=40, t=50, b=40),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )
    st.plotly_chart(fig, use_container_width=True)

with right_col:
    st.subheader("🔍 SHAP Degradation Drivers")
    top_features = ["Motor_current_roll_mean_30m", "TP2_roll_min_60m", "H1_filter_drop", "Oil_temperature_std"]
    scores = [0.14, 0.09, 0.05, 0.02]
    
    fig_shap = go.Figure(go.Bar(
        x=scores,
        y=top_features,
        orientation='h',
        marker=dict(color='#e74c3c')
    ))
    fig_shap.update_layout(
        title="Top Degradation Drivers (TreeSHAP)",
        xaxis_title="Attribution Score",
        yaxis_title="Sensor / Feature",
        template="plotly_dark",
        margin=dict(l=40, r=40, t=50, b=40)
    )
    st.plotly_chart(fig_shap, use_container_width=True)

# Diagnostic Narrative & Work Order Section
st.markdown("---")
st.subheader("📋 AI Diagnostic Report & Maintenance Actions")
narrative = "The APU operates within normal parameters. Telemetry signals demonstrate healthy pressure differentials across all pneumatic lines."
st.info(narrative)

work_order_text = f"""================================================================================
METRO RAILWAY MAINTENANCE WORK ORDER
================================================================================
Target Equipment: APU Compressor System ({apu_selection})
Alert Status     : NORMAL
Predicted Window: Within next 4h
Failure Risk     : 4.8%

DIAGNOSTIC SUMMARY:
--------------------------------------------------------------------------------
{narrative}

RECOMMENDED MAINTENANCE ACTIONS:
--------------------------------------------------------------------------------
1. Inspect compressor intake valve (COMP) and pressure switch actuation logic.
2. Check oil temperature levels and filter pressure differential (H1).
3. Perform static pressure drop test on main air reservoir (TP3).
4. Verify motor current draw during full compression duty cycle.

Generated by MetroPT AI Early-Warning System | Time-Series Analytics Engine
================================================================================
"""

st.download_button(
    label="📄 Download Automated Maintenance Work Order",
    data=work_order_text,
    file_name=f"Work_Order_{apu_selection.split()[0]}.txt",
    mime="text/plain"
)
